export const ActionTypes = {
    GET_USER_INFO: "GET_USER_INFO",
    GET_USER_ERROR: "GET_USER_ERROR",
    GET_SENT_GREEN_USER_INFO: "GET_SENT_GREEN_USER_INFO",
    GET_SENT_GREEN_USER_ERROR: "GET_SENT_GREEN_USER_ERROR",
    GET_YELLOW_USER_INFO: "GET_YELLOW_USER_INFO",
    GET_YELLOW_USER_ERROR: "GET_YELLOW_USER_ERROR",
    GET_MUTUAL_USER_INFO: "GET_MUTUAL_USER_INFO",
    GET_MUTUAL_USER_ERROR: "GET_MUTUAL_USER_ERROR"
}