name: CI
on: 
  push:
    branches:
      - "main"

jobs:
  Git_Pull:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/html/green-light-frontend
    steps:
      - name: add directory into safe 
        run: git config --global --add safe.directory /var/www/html/green-light-frontend
      - name: Taking Git Pull
        run: git pull

  Build:
    needs: Git_Pull
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/html/green-light-frontend
    steps:
      - name: Remove old node_modules
        run: rm -rf node-modules
      - name: Install dependencies
        run: npm install -f
      - name: Creating Build
        run: CI=false npm run build

